### ISSUE TITLE
Issue in blood glucose fluctuation code

### ISSUE THREAD

**Issue by syadlowsky** [clinicalml/gumbel-max-scm#1]
https://github.com/clinicalml/gumbel-max-scm/blob/02d6ecebb7ccb306c9757d12555b74ba12e17c2e/sepsisSimDiabetes/MDP.py#L253

Should this be capped at 4 instead of 1? It seems like this randomly sets non-diabetics BG to 'low' sometimes. Is that intentional?

**Comment by moberst** [comment]
:+1: Collecting this (and any future improvements to the simulator) into the `sim-v2` branch.
